### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by TheIronBorn** [comment]
Also it seems to me this `& 0xFF` is useless here?
https://github.com/sgbasaraner/yeelight-cli/blob/d71aa4792d62ac102278acb84cbfbed3393c4fb4/src/main.rs#L226-L228
It's already truncating the bits to `u8::max_value()` i.e. `0xFF` with `as u8`.

**Comment by TheIronBorn** [comment]
I can't get Github to stop inserting a newline at end-of-file

**Comment by sgbasaraner** [comment]
this doesn't compile as is, because there's a missing '}' at the end of main.rs file. Otherwise, I liked it a lot, it seems to hide my not knowing the language very well. I'd like to merge this if you add that missing character and maybe remove the last three commits about newline. Thanks a lot!

**Comment by TheIronBorn** [comment]
Am I mistaken or did https://github.com/sgbasaraner/yeelight-cli/pull/1/commits/f414dc6400a232a989ee22b3cd793b587eb7f2eb not add the missing `}`?

**Comment by sgbasaraner** [comment]
Oops yeah it did, my bad.

**Pull request merged**
